### ISSUE TITLE
Cannot import name `patterns`

### ISSUE THREAD

**Issue by Logmytech** [pinax/pinax-points#6]
I'm getting the following error when I try to migrate.

I'm on Django 1.11

```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/management/base.py", line 327, in execute
    self.check()
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/student/PycharmProjects/MyCouponSite/MyCouponSite/urls.py", line 29, in <module>
    url(r'^admin/', admin.site.urls),
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 280, in urls
    return self.get_urls(), 'admin', self.name
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 264, in get_urls
    url(r'^%s/%s/' % (model._meta.app_label, model._meta.model_name), include(model_admin.urls)),
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/django/contrib/admin/options.py", line 572, in urls
    return self.get_urls()
  File "/home/student/PycharmProjects/MyCouponSite/venv/lib/python3.5/site-packages/pinax/points/admin.py", line 34, in get_urls
    from django.conf.urls import patterns, url
ImportError: cannot import name 'patterns'
```

**Comment by Logmytech** [comment]
Added a fix here
https://github.com/pinax/pinax-points/pull/7

**Comment by grahamu** [comment]
Fix merged and looks good, thanks!
